# Generated by Django 3.1.3 on 2020-12-01 12:58

import apps.user.images
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='아이디')),
                ('provider', models.CharField(choices=[('default', '기본'), ('kakao', '카카오'), ('google', '구글')], default='default', max_length=20, verbose_name='플랫폼')),
                ('uid', models.CharField(blank=True, max_length=255, null=True, verbose_name='UID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='닉네임')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.user.images.path_user_image, verbose_name='이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자여부')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저 목록',
                'db_table': 'user',
            },
        ),
    ]
