# Generated by Django 3.1.2 on 2020-11-03 11:11

import apps.user.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='upload/media/test.jpg', null=True, upload_to=apps.user.images.path_user_image, verbose_name='이미지'),
        ),
    ]
