# Generated by Django 3.1.2 on 2020-11-03 11:11

import apps.post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_auto_20201101_2330"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like_users",
            field=models.ManyToManyField(
                related_name="like_users",
                through="post.PostLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mediacontent",
            name="file",
            field=models.ImageField(upload_to=apps.post.images.path_post_image),
        ),
    ]
