# Generated by Django 3.1.3 on 2020-11-21 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0007_auto_20201121_0722"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "댓글", "verbose_name_plural": "댓글 목록"},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="post",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.comment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=100, verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="comment",
            table="post_comment",
        ),
        migrations.DeleteModel(
            name="ReComment",
        ),
    ]
