# Generated by Django 3.1.3 on 2020-11-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_auto_20201122_0118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.post",
            ),
        ),
    ]
