# Generated by Django 3.1.3 on 2020-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=150, verbose_name='제목')),
                ('priority', models.IntegerField(default=0, verbose_name='우선순위')),
            ],
            options={
                'verbose_name': '미션',
                'verbose_name_plural': '미션 목록',
                'db_table': 'mission',
            },
        ),
    ]
