# Generated by Django 3.1.3 on 2020-11-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': '미션', 'verbose_name_plural': '미션 목록'},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='level',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='title',
        ),
        migrations.AddField(
            model_name='mission',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='우선순위'),
        ),
        migrations.AlterModelTable(
            name='mission',
            table='mission',
        ),
    ]
