# Generated by Django 3.1.3 on 2020-11-20 18:46

import apps.badge.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileicon',
            options={'verbose_name': '프로필 아이콘', 'verbose_name_plural': '프로필 아이콘 목록'},
        ),
        migrations.AlterModelOptions(
            name='userprofileicon',
            options={'verbose_name': '사용자 프로필 아이콘', 'verbose_name_plural': '사용자 프로필 아이콘 목록'},
        ),
        migrations.AddField(
            model_name='profileicon',
            name='active_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.badge.images.path_profile_icon_image, verbose_name='활성이미지'),
        ),
    ]
