# Generated by Django 3.1.3 on 2020-11-20 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_auto_20201121_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileicon',
            name='acquired_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='획득날짜'),
            preserve_default=False,
        ),
    ]
