# Generated by Django 3.1.2 on 2020-11-03 11:11

import apps.article.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20201101_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_users',
            field=models.ManyToManyField(related_name='like_users', through='article.ArticleLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='file',
            field=models.ImageField(upload_to=apps.article.models.upload_to),
        ),
    ]
