# Generated by Django 3.1.2 on 2020-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201103_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='media_contents',
            field=models.ManyToManyField(blank=True, to='article.MediaContent'),
        ),
    ]
