# Generated by Django 3.1.3 on 2020-11-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_recomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_comments', to='article.comment'),
        ),
    ]
